### ISSUE TITLE
Cannot see older commit history

### ISSUE THREAD

**Issue by PavanNiddapu** [AzeezSayed1239/Python-Project#1]
I cannot see older commits as there in original repo.
You can see how to keep them instead of a fresh new commit.
Moreover, I cannot determine what changes you made for the new proposed API
@AzeezSayed1239

**Comment by PavanNiddapu** [comment]
@AzeezSayed1239 Make the master as default branch. 
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

**Comment by PavanNiddapu** [comment]
@AzeezSayed1239  Seems like you have converted default branch to master.
Once the issue is done and you can intimate the person to verify and close the issue

**Comment by AzeezSayed1239** [comment]
Made master as the default branch
